name: Update Blog Posts
  

on:
  push:
      branches:
        - master  # 또는 워크플로우를 트리거하고 싶은 브랜치 이름
  schedule:
    - cron: '10,30,50 * * * *'  # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name 's2jin'
        git config --global user.email 'nous645@gmail.com'
        git push https://s2jin${{ secrets.GH_PAT }}@github.com/s2jin/test_blog.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython markdownify

    - name: Run script
      run: python .github/workflows/update_blog.py
